"""add request metadata to usage events

Revision ID: a4566f4b09b7
Revises: f12255966383
Create Date: 2026-02-04 23:46:08.101238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4566f4b09b7'
down_revision: Union[str, None] = 'f12255966383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_events', sa.Column('request_id', sa.String(length=64), nullable=True))
    op.add_column('usage_events', sa.Column('client_ip', sa.String(length=64), nullable=True))
    op.add_column('usage_events', sa.Column('user_agent', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_events', 'user_agent')
    op.drop_column('usage_events', 'client_ip')
    op.drop_column('usage_events', 'request_id')
    # ### end Alembic commands ###
